### ISSUE TITLE
bstats.org down

### ISSUE THREAD

**Issue by Meronat** [BtoBastian/bStats#10]
I cannot open bstats, instead I get a cached version hosted by Cloudflare. 

![image](https://cloud.githubusercontent.com/assets/18372958/22178198/ecd4ee64-dff5-11e6-9454-998f3481cc5d.png)

**Comment by BtoBastian** [comment]
Hey,

I'm sorry for the inconvenience. My hoster (contabo.de) currently has some network issues (again -.-) and there's nothing I can do about it. I'm planning on switching to an other hoster (nitrado.net) which is way more reliable, but it will take some time.

**Comment by Meronat** [comment]
Okay thanks for the quick response, good luck switching over.

**Comment by BtoBastian** [comment]
The website is back online.
