### ISSUE TITLE
Plugin page links are case sensitive

### ISSUE THREAD

**Issue by Meronat** [BtoBastian/bStats#11]
I don't know if this is intentional or not, but sometimes I try to get to a plugin's page by just typing in the link but it seems they are case sensitive. Personally I feel like it should ignore case but I am fine with it staying how it is if it is intended. 

For example my plugin Latch can be found here: https://bstats.org/plugin/sponge/Latch

but it gives me an "unknown plugin" error when I switch "Latch" to "latch": https://bstats.org/plugin/sponge/latch

**Comment by BtoBastian** [comment]
Yes,
You're right, there's no real reason for it being case sensitive. I'll change it .

**Comment by BtoBastian** [comment]
Done :)
