### ISSUE TITLE
[Question] Status of the Maven repo

### ISSUE THREAD

**Issue by timbru31** [BtoBastian/bStats#12]
Hi there,

thanks for the alternative to MCStats, since it's down again for several days, I'm currently looking for alternatives I can use and stumbled upon the relative young project bStats 👍 

What's your priority (and possible ETA) for the maven repository?
It's important for me, since it's much easier for me to check for updates. Currently I need to manually check if your gist updated.

Thanks,
Tim

**Comment by BtoBastian** [comment]
Hey, 
The Maven repo hadn't a high position on my TODO list, but I can try to implement it earlier. I want to get rid of the gists anyway and replace it with a "real" GitHub project. Together with this change I'll create a Maven repository, too.

**Comment by sgdc3** [comment]
If you need sponsored hosting for the repo i know someone who can help you ;)

**Comment by BtoBastian** [comment]
I already have a repository for my other project, do this is no problem.
But I have to test a little bit with relocations, cause the class should be in a different package for every plugin.

**Comment by sgdc3** [comment]
Just let the developer relocate the package on the final pom.xml file

**Comment by timbru31** [comment]
That's the idea, I would include the jar file (in this case just one class file) via Maven and then use shade to relocate it, basically just changing the package.

**Comment by ljacqu** [comment]
Hi @BtoBastian, just to chime in, I'd be very interested in seeing a Maven repo happening as to get rid of the `Metrics` class in our codebase. Maybe a small note about shading on the Bstats website would take care of your concerns.

**Comment by BtoBastian** [comment]
Hey,
the Maven repository is now public.
All necessary information can be found here: https://bstats.org/getting-started/include-metrics

**Comment by timbru31** [comment]
@BtoBastian Could you possible create two artifacts, one for lite and one for the normal version? If noticed that both classes are shaded into my jar file.

**Comment by BtoBastian** [comment]
That's what's the minimizeJar option is meant for, but I see that it may cause problems, if you are shading other dependencies, too.
Is there even a need for the lite version in the repository? Not sure why someone wants to use the lite version, but it's something requested by a few people.

**Comment by Meronat** [comment]
I think having the lite version will please some people who have small plugins and just want basic tracking with a small file size, so I think it would be best they're both kept but separated. Especially since the Gradle shadow plugin does not have support for the `minimizeJar` functionality yet, and most of us Sponge users use Gradle. 

I was wondering why my jar was bigger now and this explains it.

**Comment by sgdc3** [comment]
He's right, minimizeJar may also cause issues with some dependencies.

**Comment by BtoBastian** [comment]
Hey,
Lite versions now have their own module. Just add "-lite" to the artifact id if you want to use the lite version (e.g. bstats-bukkit-lite).
https://github.com/BtoBastian/bStats-Metrics/commit/1e8dc6c3bf89dbf6b64c21d59bdf20ec087861ac

**Comment by sgdc3** [comment]
Thank you! ;)
