### ISSUE TITLE
Navigation image too high

### ISSUE THREAD

**Issue by InventivetalentDev** [BtoBastian/bStats#15]
The header image in the side-navigation obstructs parts of the "Navigation" subheader

![Screenshot](https://i.inventivetalent.org/2017/02/04/1b3a1dc47a_chrome.png) 

Just a minor thing, but I thought I'd mention it :)

**Comment by BtoBastian** [comment]
Hey,
the bug is fixed now. The update will be live, soon. :)
c8594eb

**Comment by BtoBastian** [comment]
![](http://i.imgur.com/TuwiVjK.png)
Well... ^^

**Comment by BtoBastian** [comment]
How much time does it need to resize a picture:
2 month... :D

**Comment by BtoBastian** [comment]
Still broken on mobile...

**Comment by BtoBastian** [comment]
My bad, I just forgot to upload it after switching to the cluster version.
