### ISSUE TITLE
Deleting chart not working

### ISSUE THREAD

**Issue by OfficialAName** [BtoBastian/bStats#18]
When i try to delete charts created by me it doesn't want to delete them. Please fix this issue!

**Comment by BtoBastian** [comment]
Hey, ist there any error message?
It works perfectly fine for me.

**Comment by OfficialAName** [comment]
Now they work, maybe there was an error? also sorry for the late response. i had some problems
FIXED

**Comment by BtoBastian** [comment]
Could reproduce it for a newly created charts.

**Comment by BtoBastian** [comment]
Fixed in e0df04e8
