### ISSUE TITLE
Add "Universal" plugin category

### ISSUE THREAD

**Issue by Phoenix616** [BtoBastian/bStats#21]
I recently looked into transferring my plugins away from mcstats and ran into the problem that I can't add plugins that run on more than just one server software. In my case I have on that runs on both, Bukkit and BungeeCord servers. (And yes, selecting nothing does not work for those wondering)

I saw that other ticket about Sponge + Bukkit support and the issue that global stats are generated from that category. This could be avoided if the type of server the plugin is running on wasn't generated by the plugin's category on the site but send directly with the metrics request.

**Comment by BtoBastian** [comment]
Hey, you just have to add your plugin twice.
One time for Bukkit and one time for Bungeecord. :-)

**Comment by Phoenix616** [comment]
Does that automatically merge the graphs for the two?

**Comment by BtoBastian** [comment]
No, otherwise the whole separation wouldn't make any sense (See https://github.com/BtoBastian/bStats/issues/9#issuecomment-272659096).

**Comment by MiniDigger** [comment]
while I agree that a universal category doesnt make much sense, it would be nice to be able to link them. 
I guess you could rename #9 or this to reflect that or just open a new issue.

**Comment by Phoenix616** [comment]
> No, otherwise the whole separation wouldn't make any sense

Yeah I don't see how it would make sense to separate them. You could just read the information on what kind of server the plugin is run from the data that the metrics class submits and have an extra graph that shows the server-software used ratio for the plugin.

Having two separate metrics page for the exact same plugin makes no sense to me.

**Comment by DylanFPS** [comment]
+1

**Comment by Phoenix616** [comment]
Maybe this could be "solved" by allowing us to link the statistics of separate platforms so that they show up on one page and we don't have to link to each statistic page individually for each implementation? (Maybe available under /plugin/<name> or /statistics/<pluginname> as the first one could conflict with plattform names?)  This page could then just show the statistics of each implementation in a column next to each other, maybe even in relation to the global share that implementation holds.

**Comment by MarkehMe** [comment]
Just some insight.. although they are the same "file" they're technically seperate. But also, do you really want your statistics for both bungee and bukkit colliding? I think you would want to keep those seperate. 

As wouldn't that go a bit out of whack with players vs. servers? Everything would be oddly duplicated.
