### ISSUE TITLE
Order pie charts

### ISSUE THREAD

**Issue by MiniDigger** [BtoBastian/bStats#22]
Currently pie char pieces are all over the place, ordering them by size would be nice:
![http://i.minidigger.me/2017/03/chrome_26_21-05-45.png](http://i.minidigger.me/2017/03/chrome_26_21-05-45.png)
I don't think that highcharts has a option for that (couldn't find something in a 5min google, wanted to write a pr 😢) so you will have to sort the data before you shove it into highcharts

**Comment by BtoBastian** [comment]
![](http://i.imgur.com/eHzIwLY.png)
Done :)

**Comment by MiniDigger** [comment]
just noticed that this only orders the first level of drilldown charts, would you mind ordering the second level too? :D

**Comment by BtoBastian** [comment]
![](http://i.imgur.com/q4MVxNQ.png)
Done :)
