### ISSUE TITLE
Error: "Unknown software"

### ISSUE THREAD

**Issue by NathanNr** [BtoBastian/bStats#25]
If you click on the server software "server implementation" of a plugin from the plugin list, you will get an error: {"error":"Unknown software"}

![bstatsbug](https://cloud.githubusercontent.com/assets/17128682/26523245/a026dc9a-4313-11e7-9473-0305eb68667e.png)

![bstatsbug](https://cloud.githubusercontent.com/assets/17128682/26523268/2ffa77f0-4314-11e7-9dbd-47b62057e1b2.png)

**Comment by BtoBastian** [comment]
Thank you :)

**Comment by BtoBastian** [comment]
Bug fixed, new bug introduced: You can no longer click on any of the software urls...

**Comment by BtoBastian** [comment]
There's nobody who's as fast as me in fixing bugs!

**Comment by NathanNr** [comment]
If you click on "Server Implementation", you will be redirected to a [page](https://bstats.org/global/server-implementation) which loads it's data forever.
![https://bstats.org/global/server-implementation](https://user-images.githubusercontent.com/17128682/52176261-92ac3f00-27b0-11e9-89ee-8cc79ac5caef.png)

**Comment by Bastian** [comment]
Hmm, I don't think this is a real issue, as you normally don't land on this page.
