### ISSUE TITLE
Opinion - Plugin name should go on same line as "Here are some stats about"

### ISSUE THREAD

**Issue by Meronat** [BtoBastian/bStats#3]
On the plugin pages, the plugin name is placed on a new line after "Here are some stats about" and this may just be me, but I feel like it looks better if it is on the same line.

Original:
![image](https://cloud.githubusercontent.com/assets/18372958/21491965/111262d2-cbc6-11e6-8871-e41c540c6b49.png)

New: 
![image](https://cloud.githubusercontent.com/assets/18372958/21491987/44c6868a-cbc6-11e6-9b47-ec8595967af4.png)

**Comment by BtoBastian** [comment]
The reason for this change mainly were mobile devices and plugins with large names.
![](http://i.imgur.com/qEB1Skm.png)

I'll try to change it for Desktop PCs :)

**Comment by tmfksoft** [comment]
Wouldn't text wrapping resolve this by pushing words onto a new line if there isn't enough space?

**Comment by DoNotSpamPls** [comment]
This line doesn't exist anymore. Close issue?
