### ISSUE TITLE
Gaps in line charts every 12 hours

### ISSUE THREAD

**Issue by BtoBastian** [BtoBastian/bStats#35]
For some reason there is a gap in the line charts exactly every 12 hours.
No clue why, but it sucks...

**Comment by Poslovitch** [comment]
Seems they disappeared... Was it related to the database?

**Comment by sgdc3** [comment]
@Poslovitch We talked about that privately, it was fixed by incrasing the db connection pool size

**Comment by sgdc3** [comment]
@BtoBastian We can close this i think

**Comment by BtoBastian** [comment]
I want to wait one or two more days, but it seems to be fixed now.
