### ISSUE TITLE
Support multi-platform plugins

### ISSUE THREAD

**Issue by Aaron1011** [BtoBastian/bStats#38]
Some plugins, such as GriefPrevention, are able to run on both Spigot and Sponge. It would be nice if it was possible to register a plugin of bStats for multiple platforms.

**Comment by BtoBastian** [comment]
Hey,
there won't be a "multi-platform" category, reasons for it can be found in these two issues:
- https://github.com/BtoBastian/bStats/issues/9
- https://github.com/BtoBastian/bStats/issues/21

Even though it sounds like a good idea at first glance, it comes with a lot of problems, which is the reason I decided to separate them in the first place.
