### ISSUE TITLE
Bstats slow

### ISSUE THREAD

**Issue by rafedup27** [BtoBastian/bStats#41]
And it doesn't show versions like "1.2.6a"!

**Comment by Derkades** [comment]
I don't have any problems. Or do you mean that it takes 5 minutes for data to display? That is by design, bStats uploads data after 5 minutes then every 30 minutes.

**Comment by MarkehMe** [comment]
bStats has been periodically down for me too, with a "500 error" showing occasionally.

**Comment by sgdc3** [comment]
The uptime seems ok https://bstats-monitor.layerwall.com

**Comment by BtoBastian** [comment]
It has some problems at xx:00 and xx:30 when it refreshes the charts.

**Comment by MarkehMe** [comment]
Ah, that makes sense.

**Comment by electronicboy** [comment]
"some problems" meaning that the site becomes completely unusable for a few minutes, and then charts don't render for a few minutes after that. as nice as bstats is, the major reason for it's adaptation was mcstats consistently being overloaded, which is where bstats appears to be heading

**Comment by Derkades** [comment]
And I don't expect any better from a service that is run for free without advertisements

**Comment by electronicboy** [comment]
if the major reason that a service is being pushed towards others is "its more stable than x", it would generally be nice if it was more stable than x.

it's easy to scream about it being free software, but that's the whole eco system where where everybody is using free tools created/maintained by others. imagine if paper/spigot did the exact same when people wanted to highlight an instability in the software.

**Comment by Derkades** [comment]
I completely agree, but I can also see why Bastian would not want to invest in more expensive servers.

**Comment by sgdc3** [comment]
The servers are powerful enought, @BtoBastian is working on a new cluster system that should provide better performance.

**Comment by BtoBastian** [comment]
Hey, you are right, the current version is really struggling a lot under the load.
I didn't work on the cluster version for a while now (because of an other project I'm maintaining), but I'll start working on it again to get rid of the downtimes, which became far more severe than expected.

**Comment by MarkehMe** [comment]
@BtoBastian do you need a hand at all? I wouldn't mind helping out.

**Comment by BtoBastian** [comment]
Hey,
thank you, but unless you have experience with both NodeJs and Redis, I don't think there's anything you can do to help me.

**Comment by BtoBastian** [comment]
The cluster update is live now and bStats is now as lighting fast again!
Quote from the Discord server:
```
== Make bStats great again! ==
Finally the cluster update is ready! So what does this mean?
== The good stuff ==
• bStats is now insanely fast (again).
• No more downtimes at xx:00 and xx:30!
• Scalability! Doesn't matter if bStats has 1 plugin with 1 server or 10'000 plugins with 100'000 servers. With the new update I can just add more nodes(/servers) in order to increase the performance.
• Fast restarts -> If I want to publish a new update a restarts takes just 1-2 seconds. In the future it might even be able to restart without downtime at all!
== The bad stuff ==
• Some features aren't complete yet:
  -> Creating custom charts doesn't work at the moment (old ones still work).
  -> Bar charts don't work.
• There are some bugs: This was a pretty big update which caused some unexpected bugs:
   -> Login is broken (I have no clue why, it worked on my testserver...)
   -> Map chart is broken
   -> Sometimes the backend crashes. These is caused by some minor bugs which are pretty easy to fix once they happen, which means the backend should be way more stable pretty soon 


This is a big step for bStats and I'm sorry for the temporary trouble it caused. However in the long run, it will be a huge improvement for bStats. 
```
