### ISSUE TITLE
Combined Global Statistics

### ISSUE THREAD

**Issue by Meronat** [BtoBastian/bStats#5]
I think it would be a good idea to have a global statistics page that is platform agnostic. 

This would include similar data to the plugin pages but with data combined from every unique server, plus a graph or two showing which server software, then maybe one showing individual versions. This can help server owners and plugin creators to analyze this data to figure out what the information is like for the whole population compared to for just one plugin.

**Comment by BtoBastian** [comment]
Hey,

The reason I separated the different platforms are the global stats. They would mess up some data, for example the amount of players. 1 player can be on a Bungeecord server AND a Bukkit/Sponge server at the same time. In this case the Global-Players graph would be worthless.

**Comment by Meronat** [comment]
Well I think not including BungeeCord/Waterfall would be the solution there, as someone will not be on a Sponge and Spigot server at the same time.
