### ISSUE TITLE
No option to reset password

### ISSUE THREAD

**Issue by robotnikthingy** [BtoBastian/bStats#54]
Hi, I created an account on bstats, and I think Firefox remembered the incorrect password because it says I entered the wrong password.

So I tried looking for an option to reset the password and there is none, which kinda sucks because I have a plugin on there and now there is no way to manage it

Can you add an option to register an email address with an account? That way if you lose your password you can recover it

**Comment by BtoBastian** [comment]
That's planned, but not implemented yet.
At the moment you have two options:
* Create a new account and I'll transfer the plugins to your new account
* Create a new account and I'll replace the password of your old account with the password of the new account, so you can use it again.

**Comment by robotnikthingy** [comment]
Thanks, I created a new account (which is RobotnikmanAlt), so if you could transfer the plugins from my old account (which is Robotnikman) I would really appreciate it.

**Comment by BtoBastian** [comment]
I replaced the password of `Robotnikman` with the password of `RobotnikmanAlt`.
You should now be able to login to your old account with the new password.

**Comment by robotnikthingy** [comment]
Thanks!
