### ISSUE TITLE
Multiple plugins not reporting to bStats?

### ISSUE THREAD

**Issue by leelawd** [BtoBastian/bStats#6]
I have 4 plugins that currently all submit information to the bStats metrics system. and 5 current plugins on my production server 

https://bstats.org/plugin/sponge/MMCReboot
https://bstats.org/plugin/sponge/MMCLogger
https://bstats.org/plugin/sponge/SimpleGamemode
https://bstats.org/plugin/sponge/mmcprefix

These are my plugins, all of which should be reporting that there is 1 server in france using it. (where mine is located), It showed this for when i tested my Reboot plugin before adding the rest and updated another plugin which included bStats.

**Comment by BtoBastian** [comment]
Hey, what's the UUID of the server?
I'll check it tomorrow.

**Comment by leelawd** [comment]
8d9aef12-fdbc-4e53-bae3-bf62359d8943

Thank you for the fast reply

**Comment by BtoBastian** [comment]
Hey,

I changed some filter settings a few minutes ago. Can you please check if your plugins now appear?
Do they run on a Bungeecord network?

**Comment by BtoBastian** [comment]
Hey again! ^^

I finally found the reason why some servers got blocked by my filters.
It's fixed now and your servers should now appear on the website. :-)

**Comment by leelawd** [comment]
Thank you for taking your time to fix this, It has appeared to be perfectly fine now :)
