### ISSUE TITLE
Ability to download/export plugin data

### ISSUE THREAD

**Issue by Foorack** [BtoBastian/bStats#64]
Preferably in a machine-readable format such as JSON.

**Comment by DoNotSpamPls** [comment]
There is already the [REST API](https://bstats.org/help/rest-api) which returns a lot of data about any plugin when requested. Also, even if this feature was implemented, how would you benefit from it?

**Comment by BtoBastian** [comment]
Like @DoNotSpamPls already said, this feature already exists.
The REST-API should allow you to Access this data from everywhere you want.
For example I wrote a Discord-bot a few days ago which can display the data:
![](https://cdn.discordapp.com/attachments/158138316187893760/430706026782654464/unknown.png)
