### ISSUE TITLE
Drilldown pie charts

### ISSUE THREAD

**Issue by WinX64** [BtoBastian/bStats#7]
Today I had a good idea for some custom data for my plugin to send, and while a simple pie was an awesome option for me, I couldn't stop thinking that a drilldown pie chart would had fit even better for that case.

If it's not much of a chore, do you think you could implement these in the future?

**Comment by BtoBastian** [comment]
Hey,

custom drilldown pies are planned for future versions :)

**Comment by BtoBastian** [comment]
Drilldowns are now supported by the backend.
You can expect an update for the Metrics classes in ~1 week :)

**Comment by BtoBastian** [comment]
Drilldown pie charts are now fully supported, both by the backend as well as the Metrics classes. :-)
