### ISSUE TITLE
Bar charts (& Column charts)

### ISSUE THREAD

**Issue by Bammerbom** [BtoBastian/bStats#8]
I want to make a basic bar chart.
The usecase is, my plugin has different modules and for each module I want to see how many people are using the module.
https://gyazo.com/fa77bee4788bdef039893c13aec64027

You might also want to add column charts
I don't need this, but someone else might.
https://gyazo.com/1d8c3dd43449d0c3340877fa2e875148

**Comment by BtoBastian** [comment]
Hey,
thank you for the suggestion. :)
Bar charts are already on my TODO list.
I'll give them a higher priority because you aren't the first person asking from bar charts.

**Comment by BtoBastian** [comment]
https://github.com/BtoBastian/bStats/commit/92af2e72a386a33d95b9673d91b66b0d9f03e7f8
Will get live, soon.

**Comment by BtoBastian** [comment]
The update is now live.

**Comment by Bammerbom** [comment]
I get this error whenever I add a new bar chart on the website:
{"error":"Missing action"}

**Comment by BtoBastian** [comment]
https://github.com/BtoBastian/bStats/commit/9b67856012524f92772ffe8e08caf17db44cdcf7
Please try again :)

**Comment by Bammerbom** [comment]
Worked, thanks.
