### ISSUE TITLE
Bukkit and Sponge together

### ISSUE THREAD

**Issue by Bammerbom** [BtoBastian/bStats#9]
I have a plugin called UltimateCore, which is available for both Bukkit and Sponge.
Both plugins send the same data, and I would like a way to combine the bukkit and sponge plugin into one, instead of both seperate plugins.
So one page which shows both data for the Bukkit and for the Sponge plugin.

(The bukkit plugin doesn't exist yet, the sponge plugin is at https://bstats.org/plugin/sponge/UltimateCore)

**Comment by BtoBastian** [comment]
The main reason for the separation were the global charts and Bungeecord. Throwing all data into the same charts would mess up some charts (e.g. for Bungeecord and Bukkit the player amount would be counted twice). But also software specific custom charts like in your plugin (Sponge implementation + platform (which I btw really like and want to implement as default charts, too)) are only possible if every implementation has its own stats page. I may add a feature to link them (Stats pages should be way more customizable anyway with description etc.) in the future, but I still want to be able to differ between Bukkit and Sponge plugins. This comes even more important when I start adding different platforms (maybe Pocket Edition?).

**Comment by Bammerbom** [comment]
My idea was that at bukkit the implemenation says "Spigot/Craftbukkit" and the platform just says Server, because bukkit has no client version. 
I understand why you wouldn't want bungeecord and bukkit together, but I feel like putitng Bukkit and Sponge together won't give you that many problems.

**Comment by chibill** [comment]
Sponge is Forge.

Bukkit is Bukkit.

That could be one reason...

**Comment by MarkehMe** [comment]
Late to the party, but wanted to add my 2c. I think they should be kept seperate, as you are not calculating statistics for the same plugin _technically_ - even if it is the same jar file, with shared sources.

Also @chibill, Sponge is not Forge. Sponge is Sponge. It doesn't need to run on Forge.
